# Generated by Django 6.0.1 on 2026-03-16 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_add_user_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the folder was created'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(help_text='Name of the folder', max_length=100),
        ),
        migrations.AlterField(
            model_name='folder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the folder was last updated'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='user',
            field=models.ForeignKey(help_text='The user this folder belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(help_text='Full content/body of the note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the note was created'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(blank=True, help_text='Date associated with the note', null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='folder',
            field=models.ForeignKey(help_text='The folder this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.folder'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(help_text='Title of the note', max_length=200),
        ),
        migrations.AlterField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the note was last updated'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(help_text='The user this note belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
