# Generated by Django 6.0.1 on 2026-03-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_folder_created_at_alter_folder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Full content/body of the note'),
        ),
    ]
