# Generated by Django 6.0.1 on 2026-06-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='latest_commit',
            field=models.IntegerField(default=0),
        ),
    ]
