from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .viewsets import FolderViewSet, NoteViewSet

# Create a router and register the viewsets
router = DefaultRouter()
router.register(r'folders', FolderViewSet, basename='folder')
router.register(r'notes', NoteViewSet, basename='note')

# The API URLs are automatically generated by the router
urlpatterns = [
    path('', include(router.urls)),
]
