from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .viewsets import UserViewSet
from .views import login, logout

# Create a router and register the viewsets
router = DefaultRouter()
router.register(r'users', UserViewSet, basename='user')

# The API URLs are automatically generated by the router
urlpatterns = [
    path('', include(router.urls)),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]
